### ISSUE TITLE
bug: Twitter not functioning properly

### ISSUE THREAD

**Issue by jackh-sh** [JackHumphries9/Socially#1]
Hi,
     Thank you for downloading Socially. There is an issue with the Twitter tab. Twitter is not appearing in the `<webview>`. I am not sure whether the `<webview>` is working properly or it is another issue.

**EDIT**: After a bit of debugging, I have finally discovered the issue. The issue is due to Chromium loading guest content in a strange way. Chromium is trying to swap the browsing instance when the Cross Origin Opener Policy but that doesn't work with the `<webview>` as its not supported. I have determined that it is an Electron issue and when a commit is merged to fix this, I will rebuild the binaries.

**Comment by singhpawank** [comment]
Error loading twitter
V0.5, linux mint 20

**Comment by singhpawank** [comment]
Also, telegram is not loading . Not showing anything from first time I opened the app.

**Comment by jackh-sh** [comment]
> Also, telegram is not loading . Not showing anything from first time I opened the app.

Please open another issue for this.

**Comment by jackh-sh** [comment]
Twitter has been removed from Socially so this issue is no longer a problem.
