### ISSUE TITLE
Twitter not loading

### ISSUE THREAD

**Issue by farshad-sadri** [JackHumphries9/Socially#13]
**Describe the bug**
I get the "Error loading Twitter" message and a blank screen every time I tried to open it. I have no problem on other networks so far though.

**To Reproduce**
Steps to reproduce the behavior (for me):
1. Open the app
2. Open the Twitter tab

**Expected behavior**
show the Twitter website

**Screenshots**
![image](https://user-images.githubusercontent.com/13183312/118393177-f0e44f80-b652-11eb-867c-7bdae030f30f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version 20H2

**Comment by jackh-sh** [comment]
Hi,
    See this issue [this issue](https://github.com/JackHumphries9/Socially/issues/1). Due to how this app works, Twitter doesn't like being loaded as guest content. Therefore it doesn't load. Twitter will be removed in the next version of Socially.

Thanks,
Jack
